### ISSUE TITLE
[Bug]: Crashed clicking "Back" from initial dupe screen

### ISSUE THREAD

**Issue by zivvel** [Artorp/PlanningTool#2]
### Description

ONI crashed and blamed Planning Tool & Blueprints Fixed.

The player log looks to me like this mod is the culprit.

### Steps to reproduce

I was starting a new game.  Selected SO start, radioactive ocean.  Rolled some dupes.  Decided to bump difficulty settings up.  Clicked Back.  Crashed.

### Player.log

[Player-prev.log](https://github.com/Artorp/PlanningTool/files/11614162/Player-prev.log)

**Comment by Artorp** [comment]
Thanks for the report. I was able to reproduce the bug thanks to your step-by-step description. Didn't account for this case where Game.DestroyInstance is called before the game is loaded. Fix is simple and will be out soon.
